import { UnavailableState } from '@/components/UnavailableState';

export default function AdvisoriesPage() {
  return (
    <UnavailableState
      title="Advisories"
      detail="Advisory publication depends on the report approval workflow. No advisory body is generated by a model without approved, cited platform facts behind it."
    />
  );
}
