'use client';
import {FormEvent,useState} from 'react';
type Spec={key:string;label:string;target?:string;example:object};
const ACTIONS:Spec[]=[{key:'create_case',label:'Create case',example:{title:'Investigate affected endpoint',case_type:'incident',priority:'high'}},{key:'create_investigation',label:'Create investigation',example:{title:'New intelligence hypothesis',hypothesis:'Describe the hypothesis',priority:'medium'}},{key:'create_alert_rule',label:'Create alert rule',example:{name:'KEV exposure',trigger_type:'kev_exposure',condition:{},severity:'high',cooldown_minutes:60}},{key:'acknowledge_alert',label:'Acknowledge alert',target:'Alert ID',example:{}},{key:'trigger_ingest',label:'Trigger ingestion',target:'Connector name',example:{}},{key:'generate_report',label:'Generate report',example:{template:'executive_brief',title:'Executive intelligence brief'}},{key:'create_endpoint_intent',label:'Request endpoint action',example:{agent_id:'agent-uuid',intent_type:'collect_inventory',expires_at:'2026-08-03T09:00:00Z'}},{key:'create_api_key',label:'Create API key',example:{name:'Automation client',scopes:['read'],rate_limit_per_hour:1000}}];
export function ActionWorkbench(){
 const[selected,setSelected]=useState(ACTIONS[0]);const[target,setTarget]=useState('');const[token,setToken]=useState('');const[payload,setPayload]=useState(JSON.stringify(ACTIONS[0].example,null,2));const[message,setMessage]=useState('Ready. No request has been sent.');const[busy,setBusy]=useState(false);
 function choose(key:string){const next=ACTIONS.find(x=>x.key===key)??ACTIONS[0];setSelected(next);setTarget('');setPayload(JSON.stringify(next.example,null,2));setMessage('Ready. No request has been sent.');}
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage('Submitting…');let parsed:unknown;try{parsed=JSON.parse(payload);}catch{setMessage('Payload is not valid JSON. Nothing was sent.');setBusy(false);return;}try{const response=await fetch('/api/actions',{method:'POST',headers:{'Content-Type':'application/json','X-Console-Action-Token':token},body:JSON.stringify({action:selected.key,id:target||undefined,payload:parsed})});const body=await response.json();setMessage(`${response.ok?'Accepted':'Rejected'} (HTTP ${response.status}).\n${JSON.stringify(body,null,2)}`);}catch{setMessage('Write gateway could not be reached. Outcome is unknown; check the audit log before retrying.');}finally{setBusy(false);}}
 return <form className="reference" onSubmit={submit}><label>Operator action token<br/><input type="password" required autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><label>Action<br/><select value={selected.key} onChange={e=>choose(e.target.value)}>{ACTIONS.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label>{selected.target?<label>{selected.target}<br/><input required value={target} onChange={e=>setTarget(e.target.value)}/></label>:null}<label>Request payload<br/><textarea rows={12} value={payload} onChange={e=>setPayload(e.target.value)} spellCheck={false}/></label><p><button type="submit" disabled={busy}>{busy?'Submitting…':selected.label}</button></p><pre aria-live="polite">{message}</pre></form>;
}
