"""Add identity, graph, search, command, AI evaluation, and detection capabilities.
Revision ID: 0010
Revises: 0009
"""
from __future__ import annotations
import sqlalchemy as sa
from alembic import op
revision="0010"; down_revision="0009"; branch_labels=None; depends_on=None

def audit_columns():
    return [sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)]

def upgrade()->None:
    op.create_table("users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id",ondelete="CASCADE"),nullable=False),sa.Column("email",sa.String(320),nullable=False),sa.Column("display_name",sa.String(255),nullable=False),sa.Column("oidc_subject",sa.String(512)),sa.Column("status",sa.String(24),nullable=False),sa.Column("mfa_required",sa.Boolean(),nullable=False),sa.Column("last_login_at",sa.DateTime(timezone=True)),*audit_columns(),sa.UniqueConstraint("tenant_id","email",name="uq_users_tenant_email")); op.create_index("ix_users_tenant","users",["tenant_id"])
    op.create_table("roles",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(128),nullable=False),sa.Column("description",sa.Text()),sa.Column("scopes",sa.JSON(),nullable=False),sa.Column("built_in",sa.Boolean(),nullable=False),*audit_columns(),sa.UniqueConstraint("tenant_id","name",name="uq_roles_tenant_name")); op.create_index("ix_roles_tenant","roles",["tenant_id"])
    op.create_table("role_assignments",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("role_id",sa.String(36),sa.ForeignKey("roles.id",ondelete="CASCADE"),nullable=False),sa.Column("assigned_by",sa.String(255),nullable=False),*audit_columns(),sa.UniqueConstraint("user_id","role_id",name="uq_role_assignment_user_role"))
    op.create_table("user_sessions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("token_hash",sa.String(255),unique=True,nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("ip_address",sa.String(45)),sa.Column("user_agent",sa.String(512)),*audit_columns())
    op.create_table("entity_relationships",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36)),sa.Column("source_type",sa.String(64),nullable=False),sa.Column("source_id",sa.String(255),nullable=False),sa.Column("relationship_type",sa.String(64),nullable=False),sa.Column("target_type",sa.String(64),nullable=False),sa.Column("target_id",sa.String(255),nullable=False),sa.Column("confidence",sa.Float()),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("sources",sa.JSON(),nullable=False),sa.Column("valid_from",sa.DateTime(timezone=True)),sa.Column("valid_until",sa.DateTime(timezone=True)),sa.Column("created_by",sa.String(255),nullable=False),*audit_columns(),sa.UniqueConstraint("tenant_id","source_type","source_id","relationship_type","target_type","target_id",name="uq_typed_relationship")); op.create_index("ix_relationship_source","entity_relationships",["source_type","source_id"]); op.create_index("ix_relationship_target","entity_relationships",["target_type","target_id"])
    op.create_table("entity_revisions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36)),sa.Column("entity_type",sa.String(64),nullable=False),sa.Column("entity_id",sa.String(255),nullable=False),sa.Column("revision",sa.Integer(),nullable=False),sa.Column("snapshot",sa.JSON(),nullable=False),sa.Column("actor",sa.String(255),nullable=False),sa.Column("reason",sa.Text()),*audit_columns(),sa.UniqueConstraint("tenant_id","entity_type","entity_id","revision",name="uq_entity_revision")); op.create_index("ix_revision_entity","entity_revisions",["entity_type","entity_id"])
    op.create_table("saved_searches",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(255),nullable=False),sa.Column("query",sa.String(2000),nullable=False),sa.Column("filters",sa.JSON(),nullable=False),sa.Column("is_shared",sa.Boolean(),nullable=False),*audit_columns())
    op.create_table("connector_checkpoints",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36)),sa.Column("source",sa.String(64),nullable=False),sa.Column("cursor",sa.JSON(),nullable=False),sa.Column("state",sa.String(24),nullable=False),sa.Column("last_success_at",sa.DateTime(timezone=True)),sa.Column("last_error",sa.Text()),*audit_columns(),sa.UniqueConstraint("tenant_id","source",name="uq_connector_checkpoint"))
    op.create_table("agent_commands",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),nullable=False),sa.Column("agent_id",sa.String(36),sa.ForeignKey("agents.id",ondelete="CASCADE"),nullable=False),sa.Column("intent_id",sa.String(36),sa.ForeignKey("endpoint_intents.id",ondelete="CASCADE"),unique=True,nullable=False),sa.Column("nonce",sa.String(128),unique=True,nullable=False),sa.Column("envelope",sa.JSON(),nullable=False),sa.Column("state",sa.String(24),nullable=False),sa.Column("available_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("result",sa.JSON()),*audit_columns()); op.create_index("ix_agent_commands_poll","agent_commands",["agent_id","state","available_at"])
    op.create_table("ai_evaluations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36)),sa.Column("question",sa.Text(),nullable=False),sa.Column("expected_refs",sa.JSON(),nullable=False),sa.Column("actual_refs",sa.JSON(),nullable=False),sa.Column("grounded",sa.Boolean(),nullable=False),sa.Column("score",sa.Float()),sa.Column("model",sa.String(128)),sa.Column("detail",sa.JSON(),nullable=False),*audit_columns())
    op.create_table("detection_rules",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("rule_format",sa.String(24),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("version",sa.String(32),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("attack_techniques",sa.JSON(),nullable=False),sa.Column("validation",sa.JSON(),nullable=False),sa.Column("author",sa.String(255),nullable=False),sa.Column("last_validated_at",sa.DateTime(timezone=True)),*audit_columns(),sa.UniqueConstraint("tenant_id","name","version",name="uq_detection_rule_version")); op.create_index("ix_detection_rules_tenant_status","detection_rules",["tenant_id","status"])

def downgrade()->None:
    for table in ["detection_rules","ai_evaluations","agent_commands","connector_checkpoints","saved_searches","entity_revisions","entity_relationships","user_sessions","role_assignments","roles","users"]: op.drop_table(table)
